services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: lms-app
    container_name: lms-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lms-network

  web:
    image: nginx:alpine
    container_name: lms-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lms-network

  db:
    image: mysql:8.0
    container_name: lms-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lms_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: lms_user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
